version: '3.8'

networks:
  pg-bouncer-network:
    driver: bridge

services:

  pg-bouncer-and-redis:
    container_name: pgbouncer_redis
    image: harishcs/pgbouncer-redis:latest # Replace with your actual image name and tag
    environment:
      - REDIS_SERVER=1
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - MAX_CONNECTIONS=500
      - LISTEN_PORT=6432
    volumes:
      - path-to-mount:/var/lib/redis
    ports:
      - "6432:6432" # HostPort:ContainerPort for pg-bouncer
      - "6379:6379" # HostPort:ContainerPort for Redis
    networks:
      - pg-bouncer-network
    restart: always

  postgres-db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      Listen_Addresses: '*'
    volumes:
      - path-to-mount:/var/lib/postgresql/data
    networks:
      - pg-bouncer-network
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5555
    volumes:
      - path-to-mount:/var/lib/pgadmin
    networks:
      - pg-bouncer-network
    ports:
      - "5555:5555"
